Checkout management
harshitpaliwal95/shoe-zone-ecom-app pull request #5
Opened 2022-03-25 12:15 UTC by harshitpaliwal95

2022-03-31 20:30 UTC, krgarima requested changes
Suggestions:
1. When you add the same item in the cart, instead of item appearing as 2 different items, there should be only 1 item with quantity 2 and so on.
![aq](https://user-images.githubusercontent.com/90110521/161143242-c30bfcae-173c-4f62-b2d5-d4efb953c781.JPG)

2. Same item should not appear in wishlist more than once.
![aw](https://user-images.githubusercontent.com/90110521/161143368-b927fda6-abe8-4912-bacc-28eb5a36c1ae.JPG)

3. Add a badge to wishlist and cart icon showing the number of items present in Cart and Wishlist.

2022-03-31 20:30 UTC, krgarima commented on src/pages/authPage/join.js
> +                <label for="input" className="text-medium">
In react we use `htmlFor` instead of `for`

2022-04-01 02:08 UTC, harshitpaliwal95 commented
> Suggestions:
> 
> 1. When you add the same item in the cart, instead of item appearing as 2 different items, there should be only 1 item with quantity 2 and so on.
>    ![aq](https://user-images.githubusercontent.com/90110521/161143242-c30bfcae-173c-4f62-b2d5-d4efb953c781.JPG)
> 2. Same item should not appear in wishlist more than once.
>    ![aw](https://user-images.githubusercontent.com/90110521/161143368-b927fda6-abe8-4912-bacc-28eb5a36c1ae.JPG)
> 3. Add a badge to wishlist and cart icon showing the number of items present in Cart and Wishlist.

I will start working on it

2022-04-01 04:39 UTC, Asuraking1n approved these changes
Please add a button to apply dummy credentials, it make easy for us to check the project,
Codes looks good, some changes was already pointed out by others pls correct them.

2022-04-01 11:16 UTC, harshitpaliwal95 commented
> Suggestions:
> 
>     1. When you add the same item in the cart, instead of item appearing as 2 different items, there should be only 1 item with quantity 2 and so on.
>        ![aq](https://user-images.githubusercontent.com/90110521/161143242-c30bfcae-173c-4f62-b2d5-d4efb953c781.JPG)
> 
>     2. Same item should not appear in wishlist more than once.
>        ![aw](https://user-images.githubusercontent.com/90110521/161143368-b927fda6-abe8-4912-bacc-28eb5a36c1ae.JPG)
> 
>     3. Add a badge to wishlist and cart icon showing the number of items present in Cart and Wishlist.

its resolve now

2022-04-01 11:17 UTC, merged